
    import * as THREE from 'three';
    import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
    const canvas=document.getElementById('eyeCanvas'),viewer=document.getElementById('viewer'),loading=document.getElementById('loading'),partPanel=document.getElementById('partPanel'),partTitle=document.getElementById('partTitle'),partDescription=document.getElementById('partDescription'),labelsLayer=document.getElementById('labelsLayer');
    const info={cornea:{title:'Cornea',description:'The transparent curved front surface of the eye. Together with the lens, it bends incoming light toward the retina.'},iris:{title:'Iris & Pupil',description:'The colored iris adjusts pupil diameter, controlling how much light reaches the inside of the eye.'},lens:{title:'Lens',description:'A transparent biconvex structure that changes curvature during accommodation to sharpen near and far vision.'},retina:{title:'Retina',description:'A thin neural layer lining the back of the eye. Photoreceptors convert light into electrical signals for the brain.'},sclera:{title:'Sclera',description:'The tough white outer coat of the globe. It protects the eye, maintains shape and anchors extraocular muscles.'},vitreous:{title:'Vitreous Body',description:'A clear gel occupying most of the eye behind the lens, helping maintain globe shape while transmitting light.'},ciliary:{title:'Ciliary Body',description:'A muscular ring around the lens. Its action changes lens tension and contributes to aqueous humor production.'},optic:{title:'Optic Nerve',description:'A bundle of retinal ganglion-cell axons carrying visual signals from the eye toward the brain.'},choroid:{title:'Choroid',description:'A vascular, pigmented layer between sclera and retina that supplies the outer retina and absorbs stray light.'}};
    const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.localClippingEnabled=true;
    const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x07131d,.036);const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(.2,.28,8.6);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.055;controls.enablePan=false;controls.minDistance=3.4;controls.maxDistance=13.5;controls.autoRotate=false;controls.autoRotateSpeed=.32;
    scene.add(new THREE.HemisphereLight(0xffffff,0x443c38,1.65));const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(4.5,5.5,6.5);scene.add(key);const rim=new THREE.PointLight(0xdcecff,12,20,2);rim.position.set(-5,1.5,4);scene.add(rim);const violet=new THREE.PointLight(0xffdac1,10,18,2);violet.position.set(4,-3,-2);scene.add(violet);const back=new THREE.PointLight(0xff8a6b,12,14,2);back.position.set(-2,1,-5);scene.add(back);
    const eye=new THREE.Group();eye.rotation.set(-.08,-.14,-.02);scene.add(eye);const interactive=[],pieces=new Map(),labelDefs=[];const clipFront=new THREE.Plane(new THREE.Vector3(0,0,-1),1.12),clipSide=new THREE.Plane(new THREE.Vector3(-1,0,0),.05);let cutaway=false,exploded=false,labelsOn=false;
    const phys=(o={})=>new THREE.MeshPhysicalMaterial({roughness:.42,metalness:0,clearcoat:.18,clearcoatRoughness:.22,...o});
    function createLabel(text,k){const el=document.createElement('div');el.className='model-label';el.textContent=text;el.dataset.key=k;el.style.pointerEvents='none';el.style.cursor='pointer';el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Show ${text} details`);const activate=e=>{e.preventDefault();e.stopPropagation();selectPart(k,false)};el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('click',activate);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){activate(e)}});labelsLayer.appendChild(el);return el}
    function register(mesh,k,off=new THREE.Vector3(),labelPos=null){mesh.userData.key=k;mesh.userData.basePosition=mesh.position.clone();mesh.userData.explodeOffset=off.clone();interactive.push(mesh);if(!pieces.has(k))pieces.set(k,[]);pieces.get(k).push(mesh);if(labelPos)labelDefs.push({key:k,object:mesh,local:labelPos.clone(),element:createLabel(info[k]?.title||k,k)});return mesh}
    // Deterministic, locally generated anatomical textures; no external image requests.
    let seed=912;const rand=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};
    function texture(w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
    const irisMap=texture(1024,1024,(ctx,w,h)=>{
      const c=w/2;ctx.fillStyle='#293d32';ctx.fillRect(0,0,w,h);
      const g=ctx.createRadialGradient(c,c,140,c,c,510);g.addColorStop(0,'#544329');g.addColorStop(.24,'#9a8050');g.addColorStop(.55,'#6e8a77');g.addColorStop(.85,'#466c66');g.addColorStop(1,'#182c2b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
      for(let i=0;i<6200;i++){const a=rand()*Math.PI*2,r=150+rand()*310,len=18+rand()*120;ctx.beginPath();ctx.moveTo(c+Math.cos(a)*r,c+Math.sin(a)*r);ctx.quadraticCurveTo(c+Math.cos(a+.018)*(r+len*.5),c+Math.sin(a+.018)*(r+len*.5),c+Math.cos(a+.006)*(r+len),c+Math.sin(a+.006)*(r+len));ctx.strokeStyle=rand()>.5?'rgba(202,195,139,.22)':'rgba(13,37,30,.30)';ctx.lineWidth=.6+rand()*2;ctx.stroke()}
      for(let i=0;i<210;i++){const a=rand()*Math.PI*2,r=200+rand()*90;ctx.beginPath();ctx.ellipse(c+Math.cos(a)*r,c+Math.sin(a)*r,2+rand()*4,5+rand()*12,a,0,Math.PI*2);ctx.fillStyle='rgba(17,35,24,.42)';ctx.fill()}
      ctx.beginPath();ctx.arc(c,c,495,0,Math.PI*2);ctx.lineWidth=24;ctx.strokeStyle='rgba(9,24,25,.65)';ctx.stroke();
    });
    const scleraMap=texture(2048,1024,(ctx,w,h)=>{ctx.fillStyle='#eee8df';ctx.fillRect(0,0,w,h);for(let i=0;i<38000;i++){const v=210+rand()*35;ctx.fillStyle=`rgba(${v},${v-6},${v-9},.12)`;ctx.fillRect(rand()*w,rand()*h,2,2)}
      function vein(x,y,angle,len,width,depth){ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<7;j++){angle+=(rand()-.5)*.5;x+=Math.cos(angle)*len/7;y+=Math.sin(angle)*len/7;ctx.lineTo(x,y);if(j===4&&depth>0)vein(x,y,angle+(rand()>.5?.65:-.65),len*.44,width*.55,depth-1)}ctx.lineWidth=width;ctx.strokeStyle=`rgba(160,53,57,${.13+width*.06})`;ctx.stroke()}
      for(let i=0;i<100;i++)vein(rand()*w,rand()*h,rand()*6.28,40+rand()*230,.6+rand()*1.6,2);
    });
    function shell(radius){const g=new THREE.SphereGeometry(radius,128,96,0,Math.PI*2,.465,Math.PI-.465);g.rotateX(Math.PI/2);return g}
    const scleraMat=phys({color:0xffffff,map:scleraMap,bumpMap:scleraMap,bumpScale:.012,roughness:.29,clearcoat:.75,clearcoatRoughness:.13,side:THREE.DoubleSide,clippingPlanes:[]}),sclera=new THREE.Mesh(shell(2.5),scleraMat);register(sclera,'sclera',new THREE.Vector3(-9,2.8,0),new THREE.Vector3(-1.7,1.05,.8));eye.add(sclera);
    const choroidMat=phys({color:0x7f2433,roughness:.62,side:THREE.DoubleSide,clippingPlanes:[]}),choroid=new THREE.Mesh(shell(2.43),choroidMat);register(choroid,'choroid',new THREE.Vector3(-3.7,2.8,0));eye.add(choroid);
    const retinaMat=new THREE.MeshPhysicalMaterial({color:0xe88763,emissive:0x4c160f,emissiveIntensity:.36,roughness:.64,side:THREE.BackSide,transparent:true,opacity:.9,clippingPlanes:[]}),retina=new THREE.Mesh(shell(2.37),retinaMat);register(retina,'retina',new THREE.Vector3(1.5,2.8,0),new THREE.Vector3(.2,1.45,-1.25));eye.add(retina);
    const vitreous=new THREE.Mesh(new THREE.SphereGeometry(2.19,64,48),new THREE.MeshPhysicalMaterial({color:0x8fdcff,transparent:true,opacity:.075,roughness:.04,transmission:.35,thickness:1.5,side:THREE.DoubleSide,depthWrite:false,clippingPlanes:[]}));register(vitreous,'vitreous',new THREE.Vector3(6.5,2.8,0),new THREE.Vector3(.7,-.95,-.5));eye.add(vitreous);
    const irisGroup=new THREE.Group();irisGroup.position.z=2.22;eye.add(irisGroup);const iris=new THREE.Mesh(new THREE.RingGeometry(.39,1.12,192,16),phys({color:0xffffff,map:irisMap,bumpMap:irisMap,bumpScale:.027,roughness:.62,side:THREE.DoubleSide}));register(iris,'iris',new THREE.Vector3(0,0,.65),new THREE.Vector3(.85,.45,0));irisGroup.add(iris);const uv=iris.geometry.attributes.uv,pos=iris.geometry.attributes.position;for(let i=0;i<uv.count;i++)uv.setXY(i,pos.getX(i)/2.24+.5,pos.getY(i)/2.24+.5);uv.needsUpdate=true;const fibers=new THREE.Mesh(new THREE.RingGeometry(.5,1.08,128,2),new THREE.MeshBasicMaterial({color:0x1b90ae,transparent:true,opacity:.28,wireframe:true,side:THREE.DoubleSide}));fibers.position.z=.008;fibers.visible=false;irisGroup.add(fibers);const pupil=new THREE.Mesh(new THREE.CircleGeometry(.395,96),phys({color:0x010305,roughness:.12,clearcoat:.7}));pupil.position.z=-.025;irisGroup.add(pupil);
    const cornea=new THREE.Mesh(new THREE.SphereGeometry(1.4,128,80,0,Math.PI*2,0,.93),new THREE.MeshPhysicalMaterial({color:0xffffff,transparent:true,opacity:.24,roughness:.035,transmission:.3,thickness:.12,ior:1.376,clearcoat:1,clearcoatRoughness:.06,side:THREE.DoubleSide,depthWrite:false}));cornea.rotation.x=Math.PI/2;cornea.position.z=1.43;register(cornea,'cornea',new THREE.Vector3(3.5,-3.2,-1.23),new THREE.Vector3(.72,.72,.6));eye.add(cornea);
    const lens=new THREE.Mesh(new THREE.SphereGeometry(.86,80,56),new THREE.MeshPhysicalMaterial({color:0xd8f4ff,transparent:true,opacity:.34,transmission:.72,thickness:1.1,roughness:.06,ior:1.41,clearcoat:.6,side:THREE.DoubleSide,depthWrite:false}));lens.scale.set(1,1,.52);lens.position.z=1.18;register(lens,'lens',new THREE.Vector3(-2.5,-3.2,-.98),new THREE.Vector3(-.72,.82,.35));eye.add(lens);
    const ciliary=new THREE.Mesh(new THREE.TorusGeometry(1.19,.18,24,96),phys({color:0x6f3048,roughness:.66,side:THREE.DoubleSide}));ciliary.position.z=1.18;register(ciliary,'ciliary',new THREE.Vector3(-5.5,-3.2,-.98),new THREE.Vector3(-.85,-.55,.18));eye.add(ciliary);for(let i=0;i<28;i++){const a=i/28*Math.PI*2;const pts=[new THREE.Vector3(Math.cos(a)*1.03,Math.sin(a)*1.03,1.18),new THREE.Vector3(Math.cos(a)*.72,Math.sin(a)*.72,1.2)];pts.forEach(p=>p.z-=1.18);ciliary.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xd9e9d6,transparent:true,opacity:.42})))}
    const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(.28,-.04,-2.22),new THREE.Vector3(.42,-.03,-2.75),new THREE.Vector3(.68,-.02,-3.32),new THREE.Vector3(1.02,.12,-3.95)]),optic=new THREE.Mesh(new THREE.TubeGeometry(curve,72,.32,28,false),phys({color:0xe7c897,roughness:.68}));register(optic,'optic',new THREE.Vector3(7,-3.2,.2),new THREE.Vector3(1.02,.5,-3.62));eye.add(optic);optic.add(new THREE.Mesh(new THREE.TubeGeometry(curve,72,.21,20,false),new THREE.MeshPhysicalMaterial({color:0xf4dcc0,roughness:.58,transparent:true,opacity:.65})));
    const vesselMat=new THREE.LineBasicMaterial({color:0x7a1b26,transparent:true,opacity:.62});for(let i=0;i<18;i++){const a=i/18*Math.PI*2+.15*Math.sin(i),pts=[];for(let j=0;j<=22;j++){const t=j/22,theta=.22+t*1.12,r=2.25,phi=a+.22*Math.sin(t*Math.PI*2+i);pts.push(new THREE.Vector3(Math.sin(theta)*Math.cos(phi)*r,Math.sin(theta)*Math.sin(phi)*r,-Math.cos(theta)*r))}retina.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),vesselMat))}
    const shadow=new THREE.Mesh(new THREE.CircleGeometry(3.7,96),new THREE.MeshBasicMaterial({color:0,transparent:true,opacity:.24,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(0,-3.05,0);scene.add(shadow);
    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let hovered=null,viewAnim=null;
    function pointerFromEvent(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1}
    function pick(){raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(interactive,false);return hits.find(h=>{const planes=h.object.material.clippingPlanes||[];return !planes.some(p=>p.distanceToPoint(h.point)<0)&&!['cornea','vitreous'].includes(h.object.userData.key)})}
    canvas.addEventListener('pointermove',e=>{pointerFromEvent(e);const h=pick()?.object||null;hovered=h;canvas.style.cursor=h?'pointer':'grab'});let down=null;canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};viewAnim=null;controls.autoRotate=false;syncRotate()});canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;down=null;pointerFromEvent(e);const h=pick();if(h)selectPart(h.object.userData.key,true);canvas.style.cursor=hovered?'pointer':'grab'});canvas.addEventListener('pointerleave',()=>{hovered=null;canvas.style.cursor='grab'});
    function selectPart(k,focus=false){if(!info[k])return;partTitle.textContent=info[k].title;partDescription.textContent=info[k].description;partPanel.classList.add('visible');for(const [key,objects] of pieces)for(const o of objects){if(o.material.emissive){o.material.emissive.setHex(key===k?0x31473e:0x000000);o.material.emissiveIntensity=key===k?.18:0}}if(focus)focusPart(k)}
    function focusPart(k){const m={cornea:[[0,.2,7.2],[0,0,1.6]],iris:[[0,.15,6.8],[0,0,1.8]],lens:[[2.8,.7,6.2],[0,0,1]],retina:[[4.8,1.25,4.5],[0,0,-.35]],sclera:[[4.8,1.4,5],[0,0,0]],vitreous:[[4.1,.8,5.2],[0,0,-.25]],ciliary:[[3.6,.7,5.7],[0,0,1]],optic:[[4.8,.7,-.1],[.55,0,-2.65]],choroid:[[4.8,1.25,4.4],[0,0,-.35]]}[k]||[[.2,.28,8.6],[0,0,0]];animateView(new THREE.Vector3(...m[0]),new THREE.Vector3(...m[1]))}
    function animateView(toPos,toTarget,duration=700){viewAnim={start:performance.now(),duration,fromPos:camera.position.clone(),toPos,fromTarget:controls.target.clone(),toTarget};controls.autoRotate=false;syncRotate()}
    document.getElementById('pupilControl').oninput=e=>{const radius=.57-Number(e.target.value)*.0036;const g=new THREE.RingGeometry(radius,1.12,192,16),uv=g.attributes.uv,p=g.attributes.position;for(let i=0;i<uv.count;i++)uv.setXY(i,p.getX(i)/2.24+.5,p.getY(i)/2.24+.5);iris.geometry.dispose();iris.geometry=g;pupil.scale.setScalar(radius/.395)};
    document.getElementById('focusControl').oninput=e=>{lens.scale.z=.52+Number(e.target.value)*.0028};
    canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();controls.autoRotate=false;syncRotate();const v=camera.position.clone().sub(controls.target);const sp=new THREE.Spherical().setFromVector3(v);if(e.key==='ArrowLeft')sp.theta-=.12;if(e.key==='ArrowRight')sp.theta+=.12;if(e.key==='ArrowUp')sp.phi-=.12;if(e.key==='ArrowDown')sp.phi+=.12;if(e.key==='+')sp.radius*=.9;if(e.key==='-')sp.radius*=1.1;sp.makeSafe();sp.radius=THREE.MathUtils.clamp(sp.radius,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(sp))}});
    const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
    function explodeCameraDistance(){const aspect=viewer.clientWidth/Math.max(viewer.clientHeight,1);return aspect<.78?56:aspect<1.2?38:25}
    function setExploded(on){exploded=on;const b=document.getElementById('explodeBtn');b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);for(const objects of pieces.values())for(const o of objects){if(o===iris)continue;o.userData.targetPosition=o.userData.basePosition.clone().add(on?o.userData.explodeOffset:new THREE.Vector3())}irisGroup.userData.targetPosition=on?new THREE.Vector3(.2,-3.2,.2):new THREE.Vector3(0,0,2.22);shadow.visible=!on;controls.minDistance=on?8:3.4;if(on){controls.maxDistance=70;const d=explodeCameraDistance();animateView(new THREE.Vector3(-1,1.6,d),new THREE.Vector3(-1,0,0),850)}else{controls.maxDistance=70;animateView(new THREE.Vector3(.2,.28,8.6),new THREE.Vector3(),760);setTimeout(()=>{if(!exploded)controls.maxDistance=13.5},820)}}
    function setCutaway(on){cutaway=on;const b=document.getElementById('cutBtn');b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);const p=on?[clipSide]:[];[scleraMat,choroidMat,retinaMat,vitreous.material,vesselMat].forEach(m=>{m.clippingPlanes=p;m.needsUpdate=true});if(on)animateView(new THREE.Vector3(5.4,1.8,5.7),new THREE.Vector3(0,0,.1),760)}
    function setLabels(on){labelsOn=on;const b=document.getElementById('labelsBtn');b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);if(!on)labelDefs.forEach(l=>{l.element.classList.remove('show');l.element.style.pointerEvents='none'})}
    function syncRotate(){const b=document.getElementById('rotateBtn');b.classList.toggle('active',controls.autoRotate);b.setAttribute('aria-pressed',controls.autoRotate)}
    document.getElementById('resetBtn').onclick=()=>{setExploded(false);setCutaway(false);partPanel.classList.remove('visible');animateView(new THREE.Vector3(.2,.28,8.6),new THREE.Vector3(),720);document.getElementById('pupilControl').value=50;document.getElementById('pupilControl').dispatchEvent(new Event('input'));document.getElementById('focusControl').value=0;lens.scale.z=.52;setLabels(false)};document.getElementById('explodeBtn').onclick=()=>setExploded(!exploded);document.getElementById('cutBtn').onclick=()=>setCutaway(!cutaway);document.getElementById('labelsBtn').onclick=()=>setLabels(!labelsOn);document.getElementById('rotateBtn').onclick=()=>{controls.autoRotate=!controls.autoRotate;syncRotate()};document.getElementById('closePart').onclick=()=>partPanel.classList.remove('visible');document.querySelectorAll('[data-focus]').forEach(c=>c.onclick=()=>{viewer.scrollIntoView({behavior:'smooth',block:'center'});const k=c.dataset.focus;if(['lens','retina','vitreous','ciliary','choroid'].includes(k)&&!cutaway)setCutaway(true);selectPart(k,true)});
    function updateLabels(){if(!labelsOn)return;const r=canvas.getBoundingClientRect(),camDir=new THREE.Vector3();camera.getWorldDirection(camDir);labelDefs.forEach(l=>{const w=l.local.clone();l.object.localToWorld(w);const p=w.clone().project(camera),inView=p.z>-1&&p.z<1&&Math.abs(p.x)<1.05&&Math.abs(p.y)<1.05;l.element.style.left=`${(p.x*.5+.5)*r.width}px`;l.element.style.top=`${(-p.y*.5+.5)*r.height}px`;l.element.classList.toggle('show',inView);l.element.style.pointerEvents=inView?'auto':'none'})}
    function resize(){const w=viewer.clientWidth,h=viewer.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(viewer);resize();
    const clock=new THREE.Clock();function render(now){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.033);if(viewAnim){const t=Math.min(1,(now-viewAnim.start)/viewAnim.duration),e=ease(t);camera.position.lerpVectors(viewAnim.fromPos,viewAnim.toPos,e);controls.target.lerpVectors(viewAnim.fromTarget,viewAnim.toTarget,e);if(t>=1)viewAnim=null}for(const objects of pieces.values())for(const o of objects)if(o.userData.targetPosition)o.position.lerp(o.userData.targetPosition,1-Math.pow(.0005,dt));if(irisGroup.userData.targetPosition)irisGroup.position.lerp(irisGroup.userData.targetPosition,1-Math.pow(.0005,dt));controls.update();updateLabels();renderer.render(scene,camera)}requestAnimationFrame(render);requestAnimationFrame(()=>requestAnimationFrame(()=>loading.classList.add('hidden')));